### ISSUE TITLE
Incompatible with ToBuyAndSell

### ISSUE THREAD

**Issue by aAndrew3030** [YeetmanLord/So-Many-Enchants#10]
Both mods seem to use the enchanting table. Not sure if this is fixable, but wanted to make you aware of the issue

[crash-2022-04-26_04.04.35-fml.txt](https://github.com/YeetmanLord/So-Many-Enchants/files/8561166/crash-2022-04-26_04.04.35-fml.txt)

**Comment by max-widmaier** [comment]
Oh dang

**Comment by max-widmaier** [comment]
So I am unsure if I can actually fix this because the mod ToBuyAndSell registers a villager block that my mod uses as which conflicts and crashes the game.

**Comment by max-widmaier** [comment]
I will make it so that if you disable the enchanter villager in the config it will prevent the crash
