### ISSUE TITLE
Bug: crashes with latest quark

### ISSUE THREAD

**Issue by GhostlyGaming** [YeetmanLord/So-Many-Enchants#11]
It gives common_installer error when run with latest quark, I made a comment but decided to put a issue as well :)

**Comment by max-widmaier** [comment]
Tysm

**Comment by max-widmaier** [comment]
Ok well this isn't actually a problem with my mod. If that mod has an issue page submit it there because there is missing code in their newest version. If they ask for technical information say that the "class BasicItem was not found"
