### ISSUE TITLE
I cant enchant items in anvil

### ISSUE THREAD

**Issue by krjencik** [YeetmanLord/So-Many-Enchants#12]
When i put an item and a vanilla level enchanted book in an anvil and try to take the final item out of the anvil, i simply cant.

extra info: strange thing is, i can enchant like this items with books, which have higher level than vanilla.

forge 40.1.20 , Minecraft 1.18.2, version of this mod: 1.4.0

**Comment by max-widmaier** [comment]
That is very weird

**Comment by krjencik** [comment]
i tested it with this mod alone...

**Comment by Yanatis** [comment]
I have the same problem and some enchants from mod doesn't work either like "Replanting" and mod is breaking name tags too (unable to rename them in anvil). If you enchant item using command this enchant will be on item, on vanila you can enchanty using book with this enchant as well, but after inatallation of the mod, same enchant is unavilabke for the item, as example pants and mending can be used, with mod i am unable to use mending book on them.

**Comment by RobinVanTol** [comment]
had the same issue, even repairing my pick didnt work. switching from version 1.4.0 ro version 1.3.2 fixed it for me

**Comment by Yanatis** [comment]
Thanks it is working

**Comment by max-widmaier** [comment]
Ok I will see what’s happening thanks!

**Comment by krjencik** [comment]
yeah, im using 1.3.2 and now it works...
But i really want the better anvil mechanics you introduced in the 1.4.0 version...

**Comment by lovebirdmic** [comment]
I believe I am having the same issue. Specifically I noticed when I went to rename stuff. It just wouldn't let me remove the item from the final product slot. I noticed if you are able to get it to show how much experience it will cost it will work however. 
Sometimes you can get it to work if you try to combine the item with an enchantment. not always, but sometimes.

**Comment by max-widmaier** [comment]
I have fixed this. Patch will be released in next update
