### ISSUE TITLE
Carnivorous Storage + item extraction mod = Crash?

### ISSUE THREAD

**Issue by lovebirdmic** [YeetmanLord/So-Many-Enchants#13]
Potential fatal crash?

I made an auto smelter in my world and was using the world normally. I also use a pipe mod. Yesterday I upgraded my input chest to be 2 enchanted trap chests, with camo and carniv storage. (so 36x2 slots)

Reloaded the world and the game began to crash every time I loaded in. Looking at the log files, it seems there might be an issue with pipe/inventory extracting mods and this one? 
`java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27`
was the error I got. (Log showed exception originated from pipe mod) I can post full log file if wanted. 
Mod also used are the [Pipez mod](https://www.curseforge.com/minecraft/mc-mods/pipez) and then trying to fix the issue I tried with [Refined Pipes](https://www.curseforge.com/minecraft/mc-mods/refined-pipes). Both produced the error. 

I'm thinking maybe the pipe mods were told there were extra slots before the enchantment mod was able to actually add those slots? Or something? Not 100% sure.

**Comment by max-widmaier** [comment]
I will see what I can do I will be doing bug fixing today

**Comment by max-widmaier** [comment]
do you think you could give me a crash log or how to recreate because i can't seem to recreate it

**Comment by max-widmaier** [comment]
Oh nvm it crashed

**Comment by max-widmaier** [comment]
Hmm this is too inconsistent you should probably just report this to those mods
