### ISSUE TITLE
Anvil Bug

### ISSUE THREAD

**Issue by ABedwarsJoke** [YeetmanLord/So-Many-Enchants#14]
**Describe the bug**
On a server when you put a item in the first slot of the anvil the server crashes

**To Reproduce**
1. Load a server
2. Place anvil
3. Put item in the first slot of anvil
4. And Crash

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Additional context**

**Comment by ABedwarsJoke** [comment]
version prior to 1.4.0 doenst crash

**Comment by max-widmaier** [comment]
Is this 1.18? Or 1.16 because my 1.18 testing seems to work just fine, and for some reason my 1.16 doesn't want to work. If you could send me a crash report that would be amazing!
