### ISSUE TITLE
mouseClicked event handler  com.electronwill.nightconfig.core.io.WritingException: An I/O error occured

### ISSUE THREAD

**Issue by Coraline774477** [YeetmanLord/So-Many-Enchants#15]
Minecraft: 1.18.2
Forge: 40.1.73
So Many Enchantments: 1.4.2

I was gonna quickly leave my game entirely to do something and come back but then the game crashed which I've already forgotten what I was about to do before the game crashed and made me leave automatically...

Everything was fine with forge 40.1.60 but something was changed between 60 and 73 which is breaking this mod which I'll have to uninstall this mod temporarily till this issue is resolved.

Anyways here's the crash report and the latest log;

https://gist.github.com/Coraline774477/7dccba11f024ba69b18e18dd795492f0#file-gistfile1-txt

[latest.log](https://github.com/YeetmanLord/So-Many-Enchants/files/9331650/latest.log)

**Comment by max-widmaier** [comment]
This should be fixed in the next update

**Comment by Coraline774477** [comment]
Hey, Ik that what I'm about to say ain't related to this issue report but the configs ain't really working correctly since I've disabled the debuff enchantments (as I like to call them) as well as re-enabled some enchantments that I had previously disabled and they're still disabled even tho I've set them to true...

Btw the original issue is fixed so thanks for that but now could you fix your configuration folders to work properly? Please?....

**Comment by max-widmaier** [comment]
Ok, I need some info because sadly my config is a little convoluted. If this is on a dedicated server you need to use the serverconfig folder and modify so_many_enchants-server.toml. If you are playing on a singleplayer or you are _hosting_ a LAN world, you need to modify in the config menu. (Please note that I am unsure how LAN works since I've never tested it, so that's really an assumption on how LAN configs work.)

**Comment by max-widmaier** [comment]
So how are you changing the config, and are you on a server or are you playing singleplayer?

**Comment by Coraline774477** [comment]
I'm not using LAN as well as I ain't on multiplayer, I'm always on singleplayer  since I don't have any friends who owns and plays java edition anyways :,(

I've edited both the common config and the server config and neither one of them are working correctly since I left the game and came back after editing both of them..
I use notepad to edit mod configs since I don't have any other editors that can edit config files of mods (except for 7Zip but I don't think I should use 7Zip for editing config files)...

Also sorry for not answering you for the past few days, I don't have any means of notifications for github except for email but I don't have notifications for email on however and I was busy continuing on make my first minecraft animation on the 17th and yesterday I basically slept all day pretty much (slept for a little too long accidentally)....

**Comment by max-widmaier** [comment]
Ah man, that sucks. Well I do hope you are enjoying the mod. I will try my best to fix this. Also, its completely fine that you didn't respond! I hope you are having fun animating. It sure can produce amazing results.

**Comment by max-widmaier** [comment]
What's the version? (I always ask this because between versions some aspects of code are different)

**Comment by max-widmaier** [comment]
Also if you have them, could you get me some game logs? I put some debug info in the log whenever the config doesn't save changes

**Comment by Coraline774477** [comment]
The version of the mod that I'm currently playing with is 1.5.0, btw I'm currently playing right now and I've just tried to change the config just a few minutes ago.

I'm looking at the latest log and I don't see anything regarding So Many Enchants's debug logs, and the thing is is if I need to enable the mod's debug setting in the config then I can't since the config isn't saving any new changes...

**Comment by max-widmaier** [comment]
The debug feature is on by default. Thanks!

**Comment by Coraline774477** [comment]
Well then I still didn't see anything regarding S.M.E's  (So Many Enchants) debug logs...oh, wait a sec...

BINGO!

[16:21:55] [Thread-0/WARN]: Configuration file C:\Users\Pwrus\AppData\Roaming\.minecraft\config\so_many_enchants-common.toml is not correct. Correcting

BUT... Those are just SME's other config files since the mod generates other config files that I think are useless which they might be causing the issue since all of the other mods configs doesn't have more than one but why a small few may have more than one is because some of the mods I play with are big which those mods may requires more than just one config file but SME is actually quite small compared to mods like Tinkers' Construct), The Twilight Forest, Grimoire Of Gaia, Vic's Modern Warfare (1.12.2), DivineRPG and Advent of Ascension aka Nevermine.

So it doesn't make any sense to me that SME needs five BAK files which sometimes those files are empty while other times they're exactly the same as the main config file which at the same time is confusing which those other files aren't really needed.

BTW one of the addon mods for TiC that I use in Cora World; The Twilight Forest/Tinkers' Construct (1.18.2 btw) possibly needs it's BAK files since it's just an addon to a bigger mod.

I'm going to let you view my entire config folder to show you what I mean

https://drive.google.com/drive/folders/1Bj9Ly_GHhXot44_1NzPh8NB8qAaXMPgm?usp=sharing

**Comment by max-widmaier** [comment]
I am kinda done with all this config stuff being stupid.
I think I'm literally going to completely rewrite the entire thing.

**Comment by Coraline774477** [comment]
Yeah, that's what I'm thinkin..
Also I know that I don't really need to apologize but I'm sorry for bringing up the whole config thing as well as it being dumb but I guess what I (and possibly many other people) have been experiencing with SME's current configuration file(s) lately with it not really saving is possibly a sign that maybe it's time to rewrite it so that both the game and forge will save the config(s) properly?.. 
Since I can tell that both the game and forge aren't saving the mod's config correctly or else I wouldn't have mentioned the config problem in the first place...

Also why I wanted you to take a look see of my entire config folder was originally to show you what the other mod configs looks like in there so that you could get an idea of what yours should look like.
If SME really needs/needed those BAK files then that's fine but to me as my honest opinion I don't really think that the mod really needs BAK files unlike some mods such as Tinker's Reforged (the addon mod that I was referring too). 

BTW I ain't no coder/mod creator but I know a little bit of how some mods work from their failures as of bugs and crashes since sometimes I take my time to read the crash reports and the logs to get a better understanding of why the game crashes or glitches when it shouldn't so that I can help fix the issue to that those issues don't come back again but I still don't fully understand the crash reports and logs since I'm not a coder nor a mod creator.

Whenever the game crashes all that I'm doing is tryin to find the mod that caused it to crash in the first place, btw I'm not saying that SME has caused any crashes recently which it hasn't ...yet...
I'm just saying when the game does crash from any mod in general.

This is unrelated but whenever I start up 1.18.2 to play on Cora World; The Twilight Forest/Tinkers' Construct that sometimes on the first startup the game crashes that's caused by Tinkers' Construct which sometimes I think that it's just forge or Tinkers' or maybe even it's core mod Mantle having a brain fart and malfunctioning on the first start up for some weird reason, could have been the numerous changes that Lex has done to forge to cause issues with Tinkers' and Knight hasn't found all of the kinks in Tinkers' old and new code yet.

I do know now that whenever the game crashes immediately on startup it's usually a mixin error while other issues/crashes during gameplay would come from OptiFine not playin nice with the other mods (rendering issues/crashes with rendering type mods such as OptiFIne/Rubidium, for an example like how rubidium was crashing with CreativeCore which the author of CreativeCore had to remove a renderer mixin to fix the error since in the crash report(s) the mod that was causing the error was CreativeCore while loading in with Rubidium).

Why I'm even talking about all of that is cause I feel like I'm not being informative enough or not being specific enough to actually resolve this config problem of yours but since I don't have access to the mod's debug files or anything that can tell us/me what's truly going on behind the scenes as to what's really causing your configs to fail to save correctly..
I've been trying to be as informative as possible but again without any more info about the problem I can't really be up most help with this especially since I lack the knowledge of coding...
I could take the time to learn how to code but I simply just don't have the time nor do I feel like that I have time to learn how to code....
So I do think that the best possible way to resolve this once and for all is to ultimately rewrite the mod's config files as a last resort/ditch effort to fix this for good.....

**Comment by max-widmaier** [comment]
Lol. You’re totally fine. You’re basically one of the most helpful and informative mod tester I could ask for. Really it was just the amount of bugs I have to fix with the config that pushed me to rewrite the dang thing. I thought I should just rewrite it now and then never have to deal with it again

**Comment by Coraline774477** [comment]
Yeah, Also thanks for those kind words and for the work you've put into the mod, Even tho I like to think to myself as just a regular player who plays modded minecraft.
Until one of the mods starts to malfunction, misbehave, unresponsive, completely broken from the gecko then I turn from just playing with the mods to being a mod tester.
But I ain't testing mods that are in their alpha state of development such as The Twilight Forest 1.19.2 which it's in it's alpha development stage which for mods like T.T.T I don't attempt to play it while it's in it's developmental state since all I wanna do is plug and play without the kinks and the bugs and ultimately without the crashes.

For an example with my recent crashes, AVA known as Alliance of Valent Arms gun mod, one of it's 1.19.2 versions was totally broken for me when I tried it out for a 1.19.2 world that I used to play on but it's redacted now, meaning I'm keeping the world and the mod list but I may/may not play on that world anymore.
What caused that world to be redacted first of all was AVA not working correctly, it would cause the screen to blacken after say a minute or so, the first time I came onto the world with AVA installed as the latest addition to Cora World Guns to possibly sorta replace Additional Guns (which A.G is an addon to CGM (Mr.Crayfish's Gun Mod)), all of the item frames that held some of the guns (as gun racks/shelves/displays) that were put around my bedroom in my mushroom treehouse close to the ceiling were either gone or invisible and then the game crashes to the server selection screen for some reason after a few minutes.

After I permanently uninstalled AVA and returned back onto Cora World Guns only to see the armor bar all glitched which possibly means that one of AVA's latest 1.19.2 versions had corrupted the world possibly since none of the pre-existing mods were causing the graphical glitches to the armor bar since everything was completely fine the last time I was on that world.
I'm no longer going to be playing with AVA anymore, even if the author fixes the issues that I've experienced because it caused the mess that it made and that world to be redacted and I ultimately lost complete interest for AVA as a whole. I would prefer Vic's Modern Warfare over Alliance of Valiant Arms any day of the week!

I ultimately replaced Cora World Guns with Coraline World Guns for 1.16.5 that has Timeless & Classics; Reforged.
Timeless & Classics used to be an addon mod for CGM but it's since been reforged to being it's own mod while still using most of CGM's code that Mr.Crayfish gave permission for the author of T&C to use as the base coding of the mod and to iterate off from and improve on Mr.Crayfishe's work in their own mod.
Soon the author of T&C will port to 1.18+ but they would want to finish reforging the mod first.

T&C;R is a prefect alternative for VMW (Vic's Modern Warfare; Contagion 2.0) since VMW may be dead by now since it's stuck on 1.12.2 for the past several years now due to Lex replacing the old rendering engine that VMW relied on so much as well as all of the improvements that Lex has done to forge over the past few years as well as lately in 1.19.

Also VMW's last developmental release has issues code wise possibly and some of it's zombies textures needs more work and it adds in more new toys (guns) to play with but nearly half of the guns in the mod are uncraftable due to them not having any recipes to craft them since most of the existing guns in the mod are/were being reworked while the new guns that were added were obviously needed testing which was why the new guns don't have a recipe to make them yet...

BTW the only way for Vic to save his mod is to completely rewrite the mod from the ground up or else he'll have to say goodbye to VMW as it dies since 1.12.2 is still in it's dying state popularity wise which soon 1.12.2 will be just like 1.7.10 as well as all of the modded versions that came before and after those versions that were very popular at their prime. 
I don't like to see such a beautiful mod such as VMW dying out but I guess it's time for the legendary minecraft gun mod to rest in peace forever, I hope that in the future somebody makes a mod similar to VMW or asks Vic for permission to keep VMW going and finally porting the big mod over to modern versions such as 1.16.5 first then 1.18.2+.

One of the reasons why Vic has never ported VMW was because he and his crew had put 5+ years of their hard work, time, resources, and their lives onto VMW, only for Lex to completely change forge by replacing the rendering engine which has impacted VMW the most which for the past few years after 1.12 Vic and his crew have refused to port to any new major version of minecraft.

But as to why they haven't uploaded any more updates for the past year or so now is possibly because they're planning on somethin big, such as finally porting the mod over to more modern versions such as 1.16 first? 
Since in the mod's description they've stated that they're thinkin about porting at long last but if my memory serves me well I think that they're gonna skip 1.13-1.16 and port to 1.17 first then 1.18+.

If I'm right then that means they're possibly rewriting the mod from the ground up before porting it over after being stuck on 1.12.2 for 4+ years which felt like forever since I love that mod so much.
VMW beats any modern day gun mod by a long shot, you should go check it out as to why I consider VMW as the best gun mod for minecraft.

Anyways, I'm glad that you've fixed the config issue, hopefully you won't have to try to fix it ever again (unless a issue pops up but hopefully not like the one that I was experiencing)
Btw I do remember that the old configuration file(s) had issues in the past which I guess most of those issues had either came back or had caused new issues further down the line which ultimately made you rewrite the entire config from the ground up in the end which I was apart of that by reporting in about my experiences with the old config.

Again, thanks for solving the problem as well as those kind words and I'm always happy to help whenever and however I can to improve the mods that I play with (with a few exceptional mods such as T.i.C and T.T.T...) so that I don't experience any issues while playing the game or even during mod loading which for me the mod loading process is always the most daunting since I don't know what may/may not happen during the mod loading process and I always hope that I make it through as well as during gameplay.
Unfortunately I'm currently going to be on 1.16.5 on Coraline World Guns which doesn't involve using modded enchantments except for what T&C adds which for now is exactly from CGM but later down the line those enchantments will ultimately be replaced with enchantments made by TheRealClumsyAlien and his(?) crew.

When I return back onto 1.18.2+ I'll be playing with the latest version of SME on Cora World; The Twilight Forest/Tinkers' Construct and Cora World (1.19.2) as well as a new world for 1.19.2 that I'll be making soon which will be a lightweight modded world which has less mods than C.W.G, C.W; T.T.T/T.I.C and Cora World (1.19.2).
I'm going onto C.W.G (1.16.5) now to continue to find the perfect spot to call home to start the playthrough off then the planning on the house then actually start playing. 

One last thing before I go, whenever I start a new world on any version of minecraft I try to find the perfect spot to call home in survival but if I'm taking too long due to the terrain and possibly other factors then I'll switch into creative mode to find the perfect spot.
Since I traditionally go into creative mode to plan out my home builds since my creative mind isn't that good in minecraft since I have other thought processes going on inside my head so it's hard for me to focus and stay focused on my main task at hand which my first task in a new world after finding the perfect spot is to plan out how the house is going to be as of how big and how many rooms it shall have depending on the terrain.
Since I rarely build against the terrain since I build with it not against it, so if I wanna build my house with trees around it then I'll do it, if I'm gonna be living in any of my favorite biomes such as the Taiga (100%), Swamp(75%), Birch Forest(40%), especially the Snowy Taiga (100%) and the Old Growth Birch Forest (50%).

BTW when I used to be a Bedrock player as well that I had made a "hardcore" world which was just a world that was set to hard difficulty from the start and I used to build ontop of a mountain which I always tried to build a appartment building ontop of it which would've been made of spruce wood which I would build it for not just myself but for my friends who plays/played on bedrock, even tho most of them had preferred to build their own homes rather than staying in one of the units of my apartment building which I always made the building big with big enough units so that there would've been plenty of room/space to move around inside as well as sorting their stuff which I always wanted to stay in the upper floor(s) cause of the good view from the highest floors and ontop of the mountain.

Note that that all was before Caves & Cliffs but I had stopped playing on bedrock before Covid started in late 2019.
I've tried to play on Minecraft for Windows on the day that The Wild Update released but I don't like how most of the mobs move as of their animations which to me looked too stiff, not smooth as in Java Edition and unnatural which felt disgusted by looking at the villagers as well as the iron golem movements for an example, I was disappointed and disgusted by bedrock edition. 
I do remember some of the mobs movements not looking too good in the past but try to get reunited with Bedrock Edition after taking a break from it for a few years while playing on Java Edition for the same amount of time/years and tell me if the animations for the mobs in Bedrock Edition looks good or not....

(?: I don't know if TheRealClumsyAlien is a boy nor girl but I won't want to be rude about that...)

**Comment by max-widmaier** [comment]
Hey I appreciate the help and really being kind is no problem. I can tell you really know your stuff when it comes to mods! (I couldn’t really read all of it, but you obviously know quite a lot about mods even though you’re not a coder.) Anyways thank you so much for all the help!

**Comment by Coraline774477** [comment]
Hey, I have some sad news about the config..
Even tho most of the enchantments are "disabled" they're apparently still obtainable in survival mode somehow instead of what you wrote in the description. 
Even tho you've rewrote the entire config but the on/off switch isn't working (at least for me possibly..), I think you should use what majrusz uses in their config which is "#Makes this enchantment obtainable in survival mode".
Also they moved their config to the server config for most of their enchantment functionalities so that possibly all of their enchantments are synchronized with other players on multiplayer/lan game which is great for world to world basis instead of how SME is with it's current config right now.
So that I can disable some enchantments on one world while the other has the disabled enchants but instead are enabled.

BTW one or two of my three 1.19.2 worlds does have other enchantment mods installed which might cause some issues with SME as well.

**Comment by max-widmaier** [comment]
Wait how are getting the enchantments?

**Comment by Coraline774477** [comment]
Sorry for the late response..
How I'm still able to obtain disabled enchants is by normal means such as the enchanting table and enchanted books.

I'm literally about to start my play session and I'm gonna be making my latest 1.19.2 world called Cora World 4 which has a similar mod list to Cora World and Cora World 3; Dungeons's mod lists. (which always has SME since having some enchants go above their vanilla limit such as Power X or Sharpness X is better than Power V or Sharpness V)
BTW I could've just opened a new issue for the config's on/off switches not working somehow but why not just tell my current issue on this one instead?

Anyways, during the play session I'll see if I still do get disabled enchants with the different enchantment mods than what the other three 1.19.2 worlds has BUT I don't think that they're at fault for what I'm experiencing.

Now to come to think about it, I've nearly disabled all of the curse/debuff enchants but a few for balancing and just cause purposes (Hunger Enchantment mostly) and those enchants ARE still disabled BUT there's still some enchantments that I did disable due to other enchantment mods having the same enchantment with smiler functionalities/effects that nearly does the same thing such as Frostbite and Ice Aspect (from a different mod).

But why disable Frostbite in favor for a similar enchantment is cause Ice Aspect from one of the other mods pretty much does the same thing as Frostbite but better and is only mutually exclusive with Fire Aspect obviously.
Sure Frostbite is good and all BUT it can't be with Sweeping Edge on swords BUT wouldn't make sense for Sweeping Edge to be applied to axes so that's one way to utilize Frostbite (as long as I have a mod that allows me to apply weapon enchants onto an axe such as Axes Are Weapons mod).
But at the end of the day I would like to have fire aspect on sword and ice aspect or similar/different name enchantment on an axe or fire on axe and ice on sword since I use Off Hand Combat for fully functional dual wielding.

Btw as I've suggested is to have a server config alongside the client config if you so choose to keep the client side config but why have a server config is to have more control over the enchantments (as of turning them on/off) per world instead of universally (client config).

Also having convocations such as issues with the mod could be moved over onto discord that may ease this old issue report that's been resolved originally, if you want too since I'm active on discord from time to time unless I run into issues while playing modded minecraft such as some disabled enchants still being obtainable through normal means and still have their effects/mechanics enabled.

**Comment by Coraline774477** [comment]
(I'm gonna post a new comment since the previous one is getting a bit too long/much to read...)
One last thing, sometimes while playing with different enchantment mods with each other sometimes they have nearly the same enchantment(s) which could sometimes possibly cause issues or one variation could override the other which is bad in some cases?

So when I do play with multiple different mods that adds their own enchantments usually I run into the most common modded enchantments, like; Berserker, Ice Aspect, Poison Aspect, Magic Protection, Night Vision, Water Breathing etc..
SME does have a few dupe enchantments with most of the enchantment mods I play with like;

Ice Aspect, Freeze and Frostbite (Ma Enchants, Mo' Enchants and Tons of Enchants) while SME has Frostbite
Night Vision (Ma Enchants, Mo' Enchants & Tons Of Enchants) while SME has Cat Vision (I disable their night vision for yours cause you've named the enchantment differently)
Water Breathing (Tons Of Enchants) while SME has Water Breathing Enchantment
Jugger-Nog (Tons Of Enchants) while SME has Health Boost (But I keep both enabled as well as Hostile Mobs And Girls (HMAG)'s Health Boost enabled as well, also Jugger-Nog goes up to five by default as well as HMAG's Health Boost, also both Ma and Mo enchants adds similar enchantments as well but I keep 'em all enabled by default)
Springy (Tons Of Enchants) while SME has Jump Boost Enchantment, etc..

Speaking of Jump Boost Enchant, even tho it's great having Jump Boost Enchantment III but if I don't want to jump that high it could get annoying at times, especially in tight spaces, so I'll just edit the config to change it's max level to one, maybe two but definitely one tho instead of three since most of the time level three is too much at least for me, or I would like to use Springy from Tons Of Enchants or a similar enchantment like Springy BUT as I'm saying that I'm pretty much unable to disable most of the enchantments for some odd reason since I can still get Frostbite in the encahntment table and sometimes on weapons from the weaponsmith villager.

So bassically the config for disabling enchantments is possibly working but only 50% as of the ones that were previously disabled/enabled but can't disable the ones that're enabled still and possibly can't enable the disabled ones however..

If I were you I would go seek some help with the config stuff, could go ask Majrusz for some assistance with the config issue in SME cause even after completely rewriting the config it's still, STILL not working the way it's intended to be, possibly due to some changes in Forge that Lex and his crew have done with Forge that's possibly messing around with how configs works yet again, or could've been Mojang that did that again..

Especially in 1.19.3+ btw...

As I've said above a few days back that I did bring/brought some unfortunate/sad news about the config and I do feel sorry for you, especially after you've rewrote the entire config once already and yet it's still being naïve and refuses to work as it's supposed too.......

**Comment by Coraline774477** [comment]
P.S... I don't really mess with SME's config to save on headaches/heartaches, especially for your sake BUT I would've told you about the config eventually yet again.....
I could just temporarily stop playing with other enchantment mods to save you and myself the headaches/heartaches of the config's current state that it's in.......
Since SME doesn't support other modded enchants yet which could possibly take time for you to add compat with other enchantment mods, if you'd like to add compat with other enchantment mods anyways......

**Comment by max-widmaier** [comment]
I think I'll follow your advice and migrate to a purely server sided config. The config format is in JSON format rather than normal TOML format. I think I will just migrate back to TOML. It seems that the config syncing between server and client has caused many issues.

**Comment by Coraline774477** [comment]
Yea, that's possibly what was going on which is/was a shame but on the other hand having server side config is great for enchantment mods.
Like I've said above that say I want to disable certain enchantments for one world while still having them enabled on another world.

So that the configuration would be per-world basis instead of universal (client side config) which I would (did) have to reconfigure some enchantments as of disabling some of them that are the same as ones from different enchantment mods or the ones that I don't exactly like which improves/enhances the overall experience per world.
Just like most of the authors of the other enchantment mods that I've mentioned above have a server side config which is great since I can configure one world to have some of their enchantments to be disabled while the other worlds would have them all enabled by default.
So now I could partially stop playing with Tool Leveling mod, but I'll still keep playing with that mod to make some of my worlds different than the others to keep them all interesting.
So that they don't get too boring, stale, and repetitive after a while if they're all the same thing.

My mod lists are similar to each other but the difference between them all is a small amount of the mods, not all of them has gun mods as well as Dungeons Suit ( a suit of mods that adds content from Minecraft Dungeons to Minecraft) and not all of them has doggy talents Next or Revamped Wolf mod etc.

I did use SME for all of them which was great BUT without diversity between them all could've gotten boring after a while which it kinda did at one point in time possibly which is why at least two of my four current 1.19.2 worlds will keep Tool Leveling cause with that mod it allows me to get higher enchantment levels by using their station block which looks like an enchantment table but it's a 3D model that looks better than the enchantment table and that block allows you to upgrade enchantments on an enchanted item to possibly higher levels than X while disallowing the ability to upgrade certain enchantments like silk touch, mending, etc, unless specified in their config if they allow those enchantments to be upgradeable.

While having to use items that has the most value to be able to upgrade the enchantments to the next level, all of the items in the game both vanilla and modded with that mod installed has a set value of worth which means I could use items that I as well as any one else would rather throw away which makes those useless items have a use or to have another use but with diminished/less worth unlike items like netherite, diamonds, emeralds and gold etc, would have higher worth.

BUT those enchantments like mending past level one won't have any effects after level one since those certain enchantments weren't designed like that which is why even at mending 32k+ would have the same effect as mending level one.

Even tho SME doesn't allow enchantments above ten by default but I'm not gonna temper with that since certain enchantments may have the same effect as level ten anyways.

Doesn't make any sense that Notch originally intended all enchantments (as of vanilla btw) to have a maximum level of 23k+ which is only possible with cheats enabled or to be opped on a multiplayer server to get level 32k+ enchantments which would only have the same effect as levels one (mending) to five (sharpness) without actually adding on more bonus effects for those higher levels.
Unlike modded with a bit more coding could allow the effects to go above their normal limits BUT to a new set limit like how you did with level ten in SME, unless specified in the config accurse.
