### ISSUE TITLE
LightBlade Enchant bug

### ISSUE THREAD

**Issue by PHAT00100** [YeetmanLord/So-Many-Enchants#16]
**Describe the bug**
When enchanted and exited the world and reentered, the attack speed returned to the same as before the enchantment.

**To Reproduce**
1.Enchant LightBlade 
2.exit the world
3.enter the world
4.Attack speed returned to the same before enchantment.

**Expected behavior**
Enter the world, the attack speed is the same as when enchanted.

**Screenshots**
before leaving the world:
![2022-09-01_15 16 32](https://user-images.githubusercontent.com/111385709/187869877-704153f3-cd24-4a13-83a2-bc9954e6690b.png)
after entering the world:
![2022-09-01_15 17 00](https://user-images.githubusercontent.com/111385709/187870240-c62de59f-4d40-46d3-894c-c8e80b04dea9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

 sorry for my bad english.

**Comment by PHAT00100** [comment]
Exit and re-enter for the second time:
![2022-09-01_18 08 51](https://user-images.githubusercontent.com/111385709/187900453-2ffdc0e3-81e4-47d8-944a-8cfc812faf72.png)
Exit and re-enter for the 3rd time:
![2022-09-01_18 09 07](https://user-images.githubusercontent.com/111385709/187900531-9a8278ff-3f2b-4c8d-bfe3-27e8ac9ad169.png)

**Comment by max-widmaier** [comment]
Hmmm I thought I fixed this…

**Comment by max-widmaier** [comment]
Fixed!
