### ISSUE TITLE
Fuel Efficiency does not apply Iron Furnaces 

### ISSUE THREAD

**Issue by Orange-Peel-Assassin** [YeetmanLord/So-Many-Enchants#18]
**Describe the bug**
Fuel Efficiency does not apply Iron Furnaces from the Iron Furnaces mod

**To Reproduce**
1. Get Fuel Efficiency book
2. Get anvil
3. Get any Iron Furnace
4. Place book and  any Iron Furnace in anvil

**Expected behavior**
Applys Fuel Efficiency to the Iron Furnaces 

**Screenshots**
![image](https://user-images.githubusercontent.com/56128431/197108456-598ab4d8-9c76-4b9b-99b7-f9fd28963e15.png)
![image](https://user-images.githubusercontent.com/56128431/197109054-38a6c77e-ab8c-43e7-9afd-37ba06f7ba11.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome & Firefox
 - Mod Version: So many Enchants!!! 1.7.0 (1.19)
 - MC Version: 1.19.2
 - Forge Version: 43.1.28

**Comment by max-widmaier** [comment]
Looks like I'll need to add comparability for iron furnaces, then.

**Comment by max-widmaier** [comment]
I think for now I might leave compatibility alone since I don't know exactly how I would implement it right now.
