### ISSUE TITLE
V0.2.1 crashs when startup

### ISSUE THREAD

**Issue by zanecek** [YeetmanLord/So-Many-Enchants#2]
Hi.
V0.2.1 crashs when startup. V0.2.0 works.

[so_many_enchants-crash-2021-11-08_23.54.21-fml.txt](https://github.com/YeetmanLord/So-Many-Enchants/files/7500720/so_many_enchants-crash-2021-11-08_23.54.21-fml.txt)

**Comment by YeetmanLord** [comment]
That is very strange, I am using windows 10 I get no crashes. Could you tell me what forge version you are using? The current mod forge version is 36.2.0

**Comment by max-widmaier** [comment]
So I need further information. I use windows 10 you're on 8.1 that might be the problem but I doubt it. The crash log is good but to understand I need a game log that can be found in (your minecraft folder)/logs/(date that it occured) - (a random number )
or if the crash occurs newly you can post latest.log.

**Comment by zanecek** [comment]
I use Win 10 Pro, Forge 36.2.5.

In crash log is crash reason "Invalid vanilla replacement", maybe this in debug log?

[11Lis2021 03:20:26.943] [Render thread/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `shulker_box`, expected `so_many_enchants`. This could be a intended override, but in most cases indicates a broken mod.
[11Lis2021 03:20:26.948] [Render thread/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Registry replacements for vanilla block 'minecraft:shulker_box' must not change the number or order of blockstates.
	Old: facing={north,east,south,west,up,down};open={true,false}
	New: facing={north,east,south,west,up,down}


[debug-1.log](https://github.com/YeetmanLord/So-Many-Enchants/files/7531120/debug-1.log)

**Comment by max-widmaier** [comment]
ahhhhh ok I'll see what I can do

**Comment by max-widmaier** [comment]
I'm sorry. I can't seem to find _why_ this happened. The blockstates of shulker boxes don't have a "open" block state. THAT'S SO WEIRD.

**Comment by zanecek** [comment]
Thx.
And maybe even a little wish.
Can you raise the maximum possible level (adjustable in config) of attack and block reach enchants to 10, pls?

**Comment by zanecek** [comment]
> Omlouvám se. Nemůžu najít, _proč se_ to stalo. Blokové stavy shulker boxů nemají „otevřený“ blokový stav. TO JE TAK DIVNÉ.

Another mod may be incompatible. I'll try to remove some from my modpack and let you know.

**Comment by max-widmaier** [comment]
No problem

**Comment by zanecek** [comment]
Hi. There are a lot of compat problems with shulkers from other mods in my modpack.

1) Game crash on startup with this mod (which adds new blockstate - "open").
https://www.curseforge.com/minecraft/mc-mods/shulker-enchantments

2) This mod for shulkerbox opening by right click dont work (not even vanilla).
https://www.curseforge.com/minecraft/mc-mods/advanced-shulkerboxes

3) This mod for shulkerbox opening from inventory dont work (not even vanilla).
https://www.curseforge.com/minecraft/mc-mods/easy-shulker-access

4) Shulkerboxes (not even vanilla) dont have dedicated tool - breaking takes a long time.

5) Your (enchanted) shulkerboxes drop nothing!

Pls, is possible, if enchant "Cavernous Storage" is disable in config, do NOTHING with any vanilla shulkerboxes (and maybe chest too)? Thanks.

**Comment by max-widmaier** [comment]
Lol, this is the reason this is a BETA mod.
I was really dumb and set the loot tables in the wrong folder. Also thanks for reporting these compatibility issues it helps a ton!

**Comment by max-widmaier** [comment]
Fixed!! That compatibility issue is no longer an issue! :)
