### ISSUE TITLE
Lang files entries needed for compat with Enchantment Descriptions mod [1.19.2 Forge]

### ISSUE THREAD

**Issue by TelepathicGrunt** [YeetmanLord/So-Many-Enchants#20]
Just a short fyi, you should add 1 line descriptions of what your enchantments do to your lang file so Enchantment Descriptions mod can show that description for players on the item! https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

here's what it currently looks like

https://imgur.com/5Y9MtSs

Adding enchantment.so_many_enchants.camouflage.desc to your lang file will make this enchantment be translated. Be sure to do all your enchantments too for best user experience!

**Comment by max-widmaier** [comment]
Hmmm, I must have missed some of the enchants in my lang file.
