### ISSUE TITLE
anvil crash

### ISSUE THREAD

**Issue by lillcait** [YeetmanLord/So-Many-Enchants#21]
**Describe the bug**
i downloaded this mod for 1.19 for my mod pack, however everytime i go to use an anvil to apply any of the enchantments once i click to put the new enchanted item in my inventory my game freezes for a few seconds then crashes

**To Reproduce**
take any armor/item and try and put any of the enchantments on it in the anvil

**Expected behavior**
well i expected for the enchant to go on my item/armor 

![image](https://user-images.githubusercontent.com/122820317/214408748-1937e44e-98f1-4888-89d3-009f3773e707.png)

**Comment by max-widmaier** [comment]
Sadly, 1.19 isn't really supported anymore. I work on 1.19.2-1.19.3. And I do remember that bug, it is fixed in later versions.
