### ISSUE TITLE
testasdfadsfasdfasdf

### ISSUE THREAD

**Issue by Kerbal-Man** [YeetmanLord/So-Many-Enchants#22]
In the console when starting my server I got
[STDOUT/]: [com.github.yeetmanlord.somanyenchants.core.events.ServerStart:onServerStart:24]: testasdfadsfasdfasdf

**To Reproduce**
1. start your server.

**Expected behavior**
testasdfadsfasdfasdf being a more professional name like onServerStart() was called or something. 

**Screenshots**
![image](https://user-images.githubusercontent.com/100152985/225933152-e4f1ac67-cf78-4272-b020-8eafe05b91df.png)

**Comment by max-widmaier** [comment]
Lol, that shouldn't be there. It's fine however, it's just a debug message.
