### ISSUE TITLE
Furnace enchant stacking not allowed but hoppers are?

### ISSUE THREAD

**Issue by Hhhh-Pain** [YeetmanLord/So-Many-Enchants#23]
**Describe the bug**
Stack enchanting furnaces break the game

**To Reproduce**
Add fast smelt to any amount of stacked furnace in an anvil.
The stacked furnaces would disappear and instead, would show that that furnace would have double the enchant.

**Expected behavior**
Something like the hoppers, where they would enchant the entire stack with the same enchant, and each hopper would carry that enchant

**Screenshots**
![image](https://user-images.githubusercontent.com/101210486/227750982-c1359b83-8b44-4d6d-b253-e15d09463f94.png)
![image](https://user-images.githubusercontent.com/101210486/227751448-a125b635-6fe4-4ac0-ba66-1e3534f9ca86.png)

**Additional context**

**Comment by Hhhh-Pain** [comment]
also, if done multiple times, this action crashes the server. I'm not a server mod so I don't know the specifics entirely, but I'm running v1.7.1 (1.16)

**Comment by max-widmaier** [comment]
You definitely shouldn't be able to put multiple of the same enchant on one item lol.
