### ISSUE TITLE
Crash with Mowzie's Mobs mod

### ISSUE THREAD

**Issue by zanecek** [YeetmanLord/So-Many-Enchants#3]
Hi. When attack reach or block reach enchant is enabled, crashs with mod
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs
if I take it "Axe of a Thousand Metals" weapon

[so_many_enchants-crash-2021-11-11_02.57.55-server.txt](https://github.com/YeetmanLord/So-Many-Enchants/files/7517744/so_many_enchants-crash-2021-11-11_02.57.55-server.txt)

[so_many_enchants-crash-2021-11-11_02.43.55-server.txt](https://github.com/YeetmanLord/So-Many-Enchants/files/7517746/so_many_enchants-crash-2021-11-11_02.43.55-server.txt)

**Comment by max-widmaier** [comment]
Fixed!
