### ISSUE TITLE
conflict with Step up mod

### ISSUE THREAD

**Issue by stickybeard** [YeetmanLord/So-Many-Enchants#4]
The step up feature of this mod https://www.curseforge.com/minecraft/mc-mods/stepup does not function when your mod is installed.  I have tried with the step up enchantment  enabled and disabled in your config.  The Stepup mod works as intended if your mod is not installed.  I noticed nothing in the log, but can provide one if you need it.

**Comment by max-widmaier** [comment]
Ok fixed
