### ISSUE TITLE
Enchanter villager inst working

### ISSUE THREAD

**Issue by Lazunichu** [YeetmanLord/So-Many-Enchants#6]
hi! im currently tweaking some stuff for the mod and i noticed that the enchanter villager doesnt work, nor the profession doesnt exist, can you please look into that

**Comment by max-widmaier** [comment]
Sure can do

**Comment by Lazunichu** [comment]
hello it seems it exist but its seem the enchanter villager wotn appear when placing the point of interest of the block, it might be some problem with it

**Comment by max-widmaier** [comment]
Thanks that helps a loyal

**Comment by max-widmaier** [comment]
Hello there! I have done some testing and I have found that it works fine. If I were you check the config to make sure the villager is enabled. If it is not enable it and restart your game. Hope that helps!
