### ISSUE TITLE
crash when SME and Mekanism is installed

### ISSUE THREAD

**Issue by coaber** [YeetmanLord/So-Many-Enchants#8]
As the title says, today i added your mod to my modpack and when i was testing some things out, going in the creative inventory and to the mekanism tab, it would crash my game. 
I reported this to mekanism and they sent me here, so i'll provide a crash report. 

Forge version: 40.0.48
Game version: 1.18.2

[crash-2022-04-14_02.23.15-client.txt](https://github.com/YeetmanLord/So-Many-Enchants/files/8485211/crash-2022-04-14_02.23.15-client.txt)

**Comment by max-widmaier** [comment]
Ok this is an easy fix I think I was just dumb thanks for the report!

**Comment by coaber** [comment]
> Ok this is an easy fix I think I was just dumb thanks for the report!

No problem!
