### ISSUE TITLE
mekanism and SmE

### ISSUE THREAD

**Issue by l34nd35** [YeetmanLord/So-Many-Enchants#9]
Hello, my friend and me. We figured out that so many enchants and mekanism are 
incompatible on the latest minecraft-version (1.18.2):

If i acrivate an resourcepack it will crash but it also crashed while join oure server
ore an singelplayer world:

We used forge (40.1.0 and also 40.0.49)
and the latest versions of mecanism and SME.

We also test it with older versions but nothing worked.
Best Regarts L34nd35 ore Leander🤯

**Comment by max-widmaier** [comment]
Do you think I could get a crash report?

**Comment by l34nd35** [comment]
We also have the big that we can’t change the language and I Test is also without optifine in an new modpack but nothing worked:

that’s the Crash log:

The game crashed whilst rendering overlay Error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null Exit-Code: -1 [18:42:07] [main/INFO]: ModLauncher running: args [--username, mr_nuss0815, --version, forge-40.0.49, --gameDir, C:\Users\Mr.Nuss\curseforge\minecraft\Instances\Solo World, --assetsDir, C:\Users\Mr.Nuss\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 967e99368f59459f89bdb9ebc0e62bd2, --accessToken, ????????, --clientId, MWRhMzAyNmEtMTlkMy00MjVlLWExYjYtZDcxMGEwOTI1Nzdj, --xuid, [2535469818246810](tel:2535469818246810), --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 40.0.49, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914] [18:42:07] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft [18:42:07] [main/INFO]: OptiFineTransformationService.onLoad [18:42:07] [main/INFO]: OptiFine ZIP file URL: union:/C:/Users/Mr.Nuss/curseforge/minecraft/Instances/Solo%20World/mods/OptiFine_1.18.2_HD_U_H7.jar%2352!/ [18:42:08] [main/INFO]: OptiFine ZIP file: C:\Users\Mr.Nuss\curseforge\minecraft\Instances\Solo World\mods\OptiFine_1.18.2_HD_U_H7.jar [18:42:08] [main/INFO]: Target.PRE_CLASS is available ... (69 kB verbleibend)

**Comment by max-widmaier** [comment]
Fixed I think
